name: neoinsight
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/tumor1.png
    - assets/images/tumor2.png
    - assets/images/tumor3.png
    - assets/images/tumor4.png
    - assets/images/tumor5.png
    - assets/images/tumor6.png
    - assets/images/tumor7.png
    - assets/images/tumor8.png
    - assets/images/tumor9.png
    - assets/images/tumor10.png
    - assets/images/tumor11.png
    - assets/images/tumor12.png
    - assets/images/tumor13.png
    - assets/images/tumor14.png
    - assets/images/tumor15.png
    - assets/images/tumor16.png
    - assets/images/tumor17.png
    - assets/images/tumor18.png
    - assets/images/tumor19.png
    - assets/images/tumor20.png
    - assets/images/tumor21.png
    - assets/images/tumor22.png
    - assets/images/tumor23.png
    - assets/images/tumor24.png
    - assets/images/tumor25.png
    - assets/images/tumor26.png
    - assets/images/tumor27.png
    - assets/images/tumor28.png
    - assets/images/tumor29.png
    - assets/images/tumor30.png
    - assets/images/Designer.png
    - assets/tumors/image1.png
    - assets/tumors/image2.webp
    - assets/tumors/image3.png
    - assets/tumors/image5.jpg
    - assets/tumors/image6.png
    - assets/tumors/image7.jpg
    - assets/tumors/image8.jpg
    - assets/tumors/image9.jpg
    - assets/tumors/image10.png
    - assets/tumors/image11.png
    - assets/tumors/image12.jpg
    - assets/tumors/image13.png
    - assets/tumors/image14.jpg
    - assets/tumors/image15.webp
    - assets/tumors/image16.webp
    - assets/tumors/image17.jpg
    - assets/tumors/image18.jpg
    - assets/tumors/image19.jpg
    - assets/tumors/image20.jpg
    - assets/tumors/image21.jpg
    - assets/tumors/image22.jpg
    - assets/tumors/image23.jpg
    - assets/tumors/image24.jpg
    - assets/tumors/image25.jpg
    - assets/tumors/image26.webp
    - assets/tumors/image27.png
    - assets/tumors/image28.jpg
    - assets/tumors/image29.png
    - assets/tumors/image30.jpg
    - assets/tumors/tumor.png
    - assets/tumors/home.png
    - assets/tumors/people.png
    - assets/images/Designer.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
flutter_native_splash:
  color: "#dfedee" # Background color of the splash screen
  image: assets/images/Designer.png
  android: true
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
